### ISSUE TITLE
Polish translations

### ISSUE THREAD

**Issue by MikKrz** [kevinpapst/kimai2#1425]
Hi 
Just finished Polish traslation for Kimai. Before release to public via  GitHub -wanted my users to review translation. But polish language does not apperar in language drop down list .
Files added in  kimai/translation  :about.pl.xlf, daterangepicker.pl.xlf,flashmessages.pl.xlf,invoice-numbergenerator.pl.xlf, messages.pl.xlf, plugins.pl.xlf, tags.pl.xlf,validators.pl.xlf,actions.pl.xlf,exceptions.pl.xlf,invoice-calculator.pl.xlf, invoice-renderer.pl.xlf,        pagerfanta.pl.xlf ,system-configuration.pl.xlf, teams.pl.xlf
Files added in kimai2/vendor/kevinpapst/adminlte-bundle/Resources/translations/  AdminLTEBundle.pl.xliff
config/packages/kimai.yaml  not adjusted  - there is no reason assuming fallback to en 
config/services.yaml adjusted 
app.js , callendar.js adjuster 
nginx reloaded . No languade in drop down .  Do I miss something  ?
Reg - Mik

**Comment by kevinpapst** [comment]
Awesome!
You can sent in a PR, then I can help finding the problem and I can install it on one of the demo subdomains. Won't take long.

Did you clear the cache? New translations will only be picked up if you do that:
```
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod
```

**Comment by MikKrz** [comment]
O yeah now I have screw it  :) 
![500](https://user-images.githubusercontent.com/60489764/73495879-b13f1900-43b7-11ea-94e7-aa219e15d4e4.png)

**Comment by kevinpapst** [comment]
LOL, check var/log/prod.log

**Comment by kevinpapst** [comment]
Often flushing the cache will break the permissions, scroll down here: https://www.kimai.org/documentation/updates.html and re-apply them

**Comment by MikKrz** [comment]
You are  right  - Failed to create \"/var/www/kimai2/var/cache/prod/translations\

**Comment by MikKrz** [comment]
Now its working  - let me review it and  I will make PR ASAP  - than You for Your help  (include that in manual :) )

**Comment by MikKrz** [comment]
Hmm all of calendar / datepickers are in Chinese 
calendar.js in assets looks like : 
require('fullcalendar');
require('fullcalendar/dist/gcal.min');

require('fullcalendar/dist/locale/ar');
require('fullcalendar/dist/locale/cs');
require('fullcalendar/dist/locale/da');
require('fullcalendar/dist/locale/de');
require('fullcalendar/dist/locale/de-ch');
require('fullcalendar/dist/locale/es');
require('fullcalendar/dist/locale/eu');
require('fullcalendar/dist/locale/fr');
require('fullcalendar/dist/locale/hu');
require('fullcalendar/dist/locale/it');
require('fullcalendar/dist/locale/ja');
require('fullcalendar/dist/locale/ko');
require('fullcalendar/dist/locale/nl');
require('fullcalendar/dist/locale/pt-br');
require('fullcalendar/dist/locale/ru');
require('fullcalendar/dist/locale/sk');
require('fullcalendar/dist/locale/sv');
require('fullcalendar/dist/locale/tr');
require('fullcalendar/dist/locale/zh-cn');
require('fullcalendar/dist/locale/pl');

require('fullcalendar/dist/fullcalendar.min.css');

**Comment by kevinpapst** [comment]
Thats okay. You have to recompile all assets in order to see these changes (see developer docs) or I will do it when the PR is there.

**Comment by MikKrz** [comment]
Any luck with that assets ? I did something wrong with PR ? That s my debut  on GitHub :)

**Comment by kevinpapst** [comment]
I had to prepare some other things first. Give me some time, I am on other tasks right now.
I'll let you know once I updated the demo.

**Comment by kevinpapst** [comment]
Can be tested at https://demo-branch.kimai.org/pl/login with `susan_super` and `kitten`

**Comment by MikKrz** [comment]
Thank  You -  i can see a small  misspelling wilco with translation. There is one issue  on datepicker  - for some reason names of the month are displayed as "name|declension of name" see below 
![image](https://user-images.githubusercontent.com/60489764/73561318-10a13580-4459-11ea-90c2-8b523fdb3416.png)

in this (january) case proper translation schould be styczeń not stycznia|styczeń. Can I fix it somehow ? Its unreadeable that way

**Comment by kevinpapst** [comment]
I have no clue where this is coming from. 
The datepicker is using moments to render the days, see this: 
https://github.com/kevinpapst/kimai2/blob/master/assets/js/plugins/KimaiDateTimePicker.js#L46

So I'd say one of both libs have a problem with `pl` locale. But this is just an educated guess.

**Comment by MikKrz** [comment]
hmm whole list is somehow wrong  
![image](https://user-images.githubusercontent.com/60489764/73580854-6f7da380-4487-11ea-81a2-fd3585a69224.png)

**Comment by kevinpapst** [comment]
I found the reason and posted an issue with momentjs at https://github.com/moment/moment/issues/5369 

I'll try to apply an easy workaround.

**Comment by kevinpapst** [comment]
Reinstalled, please try again (maybe not only polish, to make sure no other language broke).

**Comment by MikKrz** [comment]
Its ok now  -  checked on all slavic languages as well - shoud I update my local  test from GH ? We are constanly  working  on traslation minor errors .

**Comment by kevinpapst** [comment]
Yes, you can safely pull from GH. I didn't change anything in the translations, just other files.
And then commit & push your changes, so I can reinstall the demo

**Comment by MikKrz** [comment]
Minor  : in user profile / Display.colours  , Display.layout values are in english

**Comment by kevinpapst** [comment]
Yes, in every language. Same for the doctor page. Some elements can't be translated as I didn't thought it was worth the effort.

**Comment by MikKrz** [comment]
Yeah - We can live with that nopro - i was afraid i've  skipped something .  Forgive my newbie question: should I use git-clone  on whole repo  ? Git -fetch /checkout did and asset rebuild sequence did not downloaded Your changes  to my instance :)

**Comment by kevinpapst** [comment]
`git pull` should do the work.

But if `git status` reports local changes, then my change will probably not be applied to your system. You have to merge then.

**Comment by MikKrz** [comment]
Definitly to green to do that  :) Maybe  I should pull it  from "my"  fork of Your repo . Will do it hard way  - and read about it in meantime

**Comment by MikKrz** [comment]
One more - i can not dig it out . in admin / client  /(someclient ) /Bugdet  variable %activities% is schon as variable name instead of value . Can't  find a trash 
![image](https://user-images.githubusercontent.com/60489764/73592145-7512d200-44f7-11ea-85fe-f8b32ec38c06.png)

Thats in messages.pl.xlf  admin_customer.short_stats . Strange i ve copied it from admin_project.short_stats , admin_activity.short_stats ( those are ok)

**Comment by kevinpapst** [comment]
Yeah, git can be tricky, especially in the beginning. But there are many great tutorials out there.
I can try to help with the git steps if you can't get it updated. I added my changes to your fork, thats why I said a `git pull` should be enough. 

If something doesn't work, always check English first. For some (stupid) reason the replacer variable is called `%activity%` for customers and in projects it is called `%activities%`. 
Actually it seems to be wrong translated in 4 languages.

**Comment by MikKrz** [comment]
Activity solved . So You mean I should pull from my repo not  Yours ?

**Comment by kevinpapst** [comment]
Yes. You did a "git push" before you opened the PR in your fork. I added my changes to your fork. So a git pull should be enough.

**Comment by MikKrz** [comment]
Hufsh . I ve dragged files manually to git www interface :) Like last mooron - Time to Learn  :)

**Comment by kevinpapst** [comment]
Hahaha 🎉  Oh well  ... okay, try this: https://desktop.github.com
Might be simpler than learning git from the command line

**Comment by MikKrz** [comment]
Managed to use  command  line . I am not using lapmp stack -  vi rulez - working on real hosted server.  Put some minor changes  to  my repo , lots of typos fixed - worth  to be published to test site imho.

**Comment by kevinpapst** [comment]
You have overwritten the kimai.yaml with some invalid changes and changed the default widgets:
https://github.com/kevinpapst/kimai2/pull/1426/commits/061c915a3b79ca2d651e0d1db8f0f19294d50b2c#diff-a4c4c3e459663533af7607848e15e457

**Comment by MikKrz** [comment]
Oops  - should I  change it  or You are able to do that  ?

**Comment by kevinpapst** [comment]
I am in the middle of something completely different. When you fix it, I can re-install the demo

**Comment by MikKrz** [comment]
Fixed -(hope so )

**Comment by kevinpapst** [comment]
no, you changed the PL definition, but the widgets are still wrong:
https://github.com/kevinpapst/kimai2/pull/1426/files#diff-a4c4c3e459663533af7607848e15e457

Overwrite it with the version from master and the re-add the PL config part

**Comment by MikKrz** [comment]
Strange - I dont get it  When I create copy fresh copy from command line  (git clone -b 1.7 --depth 1 https://github.com/kevinpapst/kimai2.git or just git clone https://github.com/kevinpapst/kimai2.git)  dashboard section on kimai.yaml looks like  :
 dashboard:
        user_duration:
            title: stats.yourWorkingHours
            order: 10
            permission: view_own_timesheet
            type: '\App\Widget\Type\CompoundChart'
            widgets: [DailyWorkingTimeChart, userDurationToday, userDurationWeek, userDurationMonth, userDurationYear]

Using desktop  - then scp to right place  did the job

**Comment by kevinpapst** [comment]
If you clone version 1.7 then you get the old version, but "master" branch looks like this:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L180

**Comment by kevinpapst** [comment]
Dashboard fixed, but now the permissions are wrong 😁 
https://github.com/kevinpapst/kimai2/pull/1426/files#diff-a4c4c3e459663533af7607848e15e457

**Comment by MikKrz** [comment]
Gimme a hamer :) Now cloned with -b master

**Comment by kevinpapst** [comment]
Hahaha, I see the effort. Git is a bitch if you don't really understand the basics.
I can fix it for you, if it won't work. Actually you could simply copy the contents from the file directly from the browser and then commit that. No need to clone it over and over again.
I reinstalled the demo, so you can have a look.

**Comment by MikKrz** [comment]
Yeah thats kinda frustrating Ctrl-C Ctrl-V hmmm i did that but from Git desktop, not browser
