### ISSUE TITLE
Changes in Doctrine with Kimai 1.15.3 cause 503 errors

### ISSUE THREAD

**Issue by pbksol** [kevinpapst/kimai2#2966]
First, I have to admit that I'm a bit lazy when it comes to updating the Kimai core – Plugins as soon as possible but not the core.

Some days ago I decided to update Kimai from *cough* 1.15.1 to the latest version. And this is where things started to go down the drain. Some operations where performed once and then quitted with a 503 error. Clearing the Kimai cache allowed exactly one operation and then failed again.

Same with API calls. The first request got a 200, the second one a 503.

No PHP errors where thrown.

I was able to duplicate the behaviour by just opening the calendar. First click worked, second quitted with a 503.

I then reverted back to 1.15.1 and everything was back to normal. An update to 1.15.2 did work flawlessly, too.

The errors came back when 1.15.3 was installed. Same behaviour as before.

14 days later I decided to go deep down this rabbit hole.

I installed a new Kimai instance, no data, no plugins. Version 1.15.2 worked without issues, 1.15.3 did show the exact behaviour as the "real" instance.

I then started to copy folders from the vendor folder over from 1.15.2 to 1.15.3 and long story short (or two days later)… Something seems to be badly wrong with the doctrine ORM.

If I replace the file

/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php

with the version from Kimai 1.15.2 (and only *this* one file) everything is running back stable again.

Something must have changed which now causes trouble. I checked the ORM repository but couldn't find any issue that sounds familiar.

I did not dig any deeper, but I think it might be something related to MySQL 5.7 – but I'm not sure.

Just wanted to let you know that there's something going on – I stopped digging deeper at this point.

Kimai 1.16.2 seems to be running fine with the replaced Query.php.

**Additional context**
 - PHP version: 7.4
 - MySQL 5.7

**Comment by kevinpapst** [comment]
Do you have the correct serverVersion in your connection string in .env?

**Comment by pbksol** [comment]
Yes, it's set to 5.7

**Comment by kevinpapst** [comment]
Not sure what I can do here to support you. Never seen it, sorry 🤷 
I am managing hundreds of installations and this error does not sound familiar.

**Comment by pbksol** [comment]
I don't believe it's something you can change as it seems related to ORM alone.
I'm too busy to dig any deeper at the moment.
As long as the dependency can be reverted to an earlier version everything is ok so far.

It's documented and it can be found by other people if they encounter the same problem. A least they know which file to replace :-)

**Comment by kevinpapst** [comment]
Thanks for debugging @pbksol - I hope it fixes itself with the next composer update

**Comment by daesters** [comment]
I had the same issue when update from 1.15 to 1.16.8. One tasks, and then 503 server error until reloading the cache with bin/console kimai:reload....
I can check whether I find more, but no PHP error was thrown.

**Comment by pbksol** [comment]
> I had the same issue when update from 1.15 to 1.16.8. One tasks, and then 503 server error until reloading the cache with bin/console kimai:reload....

Do you have the query.php from the previous version to replace and fix it? 

I've attached it. Rename it to Query.php and copy it into /vendor/doctrine/orm/lib/Doctrine/ORM/ – that'll provide at least a temporary fix.

[Query_old.php.zip](https://github.com/kevinpapst/kimai2/files/7694452/Query_old.php.zip)

**Comment by kevinpapst** [comment]
What a weird bug. 

Can you try to `composer update` all packages and test if new versions fix the issue for you?

**Comment by kevinpapst** [comment]
Oh and you could check if you have the ?serverVersion in your `DATABASE_URL`. Once upon a time it was not included in the Kimai release and now sometimes Doctrine gets crazy if it is missing. 
See https://github.com/kevinpapst/kimai2/blob/master/.env.dist#L2

**Comment by daesters** [comment]
Dear all

I've updated the composer packages with `composer update`. It still happens. And I checkt the DATABASE_URL, ?serverVersion is there. Might be of interesset, but the dashboard page and all the the "System" pages (Doctor, Settings, ...) work, only when loading the timesheet directly, these pages have problems: 
- "timesheet"
- "calendar"
- "team/timesheet"
- "reporting/week_by_user"
- "admin/customer/"

I really have to execute ` bin/console kimai:reload`. Any ideas, what to look for.

Version: 1.16.8 prod (Ayumi)
PHP Version 7.4.24

I'll check later with PHP8 😃

**Comment by daesters** [comment]
@pbksol Your solution (https://github.com/kevinpapst/kimai2/issues/2966#issuecomment-991161752) works quite well. Replaced the existing query code with the old one, and problem solved....
I'm checking the diff between these two files.

**Comment by pbksol** [comment]
I can tell that PHP8 will not make any difference – same behaviour.

They changed the query.php and almost replaced everything. A ton of new stuff was added and some stuff got relocated to external files.

I got sidetracked by the strict parameter with which the new version starts, but that rabbit hole seemed dead.

**Comment by daesters** [comment]
Strange, happened again when updating to 1.16.10....

**Comment by kevinpapst** [comment]
I am running not only the cloud, but also various customer installations with the latest release and never saw that error.
All running with a wild mix of PHP 7.3, 7.4 and 8 and MariaDB and MySQL.
Still thinking this must be either a PHP bug or an incompatibility with the database version.
@pbksol does a composer update work for you as well?

**Comment by pbksol** [comment]
> @pbksol does a composer update work for you as well?

I did a manual update which then again broke it. Replacing the query.php fixed it again.
Updating Kimai to 1.16.10 worked, no dependency updates necessary and everything is working rock stable so far.
But: only with the "old" query.php

**Comment by kevinpapst** [comment]
Could you try to do a composer update? 
Maybe this is a Doctrine bug that triggers only in certain scenarios and was fixed. Then I could it for everyone for the next version.

**Comment by daesters** [comment]
And 503 again!
I've run `compuser update again`. It works, but I think because the script `cache:clear` is called.
I think, next time I call `cache:clear` directly.

Probably I need to swich to the ''old'' query.php, did work with 1.16.8

**Just some thoughts and questions:**
1. I wonder, why does this only happen for the following pages
* "timesheet"
* "calendar"
* "team/timesheet"
* "reporting/week_by_user"
* "admin/customer/"

Any ideas?

2. Could it be a problem, that I run kimai2 in a subfolder, like mydomain.com/kimai2 ?


> Strange, happened again when updating to 1.16.10....
> 
> [Edit:] But this time, running `composer update` helped. I'll check for how long.
> 
> > Dear all
> > I've updated the composer packages with `composer update`. It still happens. And I checked the DATABASE_URL, ?serverVersion is there. Might be of interest, but the dashboard page and all the "System" pages (Doctor, Settings, ...) work. Only pages loading the timesheet directly have problems:
> > ```
> > * "timesheet"
> > 
> > * "calendar"
> > 
> > * "team/timesheet"
> > 
> > * "reporting/week_by_user"
> > 
> > * "admin/customer/"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I really have to execute ` bin/console kimai:reload`. Any ideas, what to look for.
> > Version: 1.16.8 prod (Ayumi) PHP Version 7.4.24
> > I'll check later with PHP8 😃

**Comment by daesters** [comment]
Still happening. A temporary solution is using ` bin/console cache:clear`.
I have to check in my free time, whether I find something in the logs....

**Comment by kevinpapst** [comment]
See, I cannot reproduce and MOST other users can't as well, otherwise this topic would be more alive.
So unfortunately one of you has to debug the issue and find something that helps. I am not saying this is not a Kimai issue, I am just saying: I have no idea how to reproduce the issue in order to fix it.

**Comment by daesters** [comment]
@kevinpapst No worries, this is in no way a demand for you to reproduce!  I more thought of it as a way to firstly document and secondly help others if they have the same issue. 
As long as I don't have any more evidence, logs, I won't post any more comments in this thread 😃

**Comment by darkol** [comment]
Hi, I have installed 1.16.10 version on cPanel Softaculus hosting yesterday and went through the initial setup.
The installation asked to change PHP from 7.3 to 7.4, I have confirmed.
All my other web apps seem to work.

A new installation of Kimai 1.16.10 has been completed. The details of the installation are shown below:
Auto Upgrade : Disabled
Automated Backups : Once a week
Backup Rotation : 5
Time of Installation : January 18, 2022, 12:17 pm

After I created first **Activity** the return to Activities returned _Error 503_.
Also **Calendar**, Administration (team) **Timesheets**, **Tags** returned _Error 503_ after first re-visit.
If I cleared cache by just removing all files and folders form var/cache/prod/ and forms except Calendar worked for first visit. Re-visit again gave _Error 503_.

Today I checked github issues and found this one and final text "**My solution**: Switching to PHP8 :)"
Thanks @daesters !

**SOLUTION:** Using PHP Selector I changed Current **PHP version to 8.0** and Kimai works.

P.S.: also forced me to upgrade Wordpress to work with PHP8 :)

**Comment by kevinpapst** [comment]
You could [try this](https://github.com/symfony/symfony/discussions/44270#discussioncomment-1989590) in [this line](https://github.com/kevinpapst/kimai2/blob/master/config/packages/prod/doctrine.yaml#L31).

@darkol sorry for the troubles, but now you are on a modern version of PHP, which is good thing anyways 😁

**Comment by darkol** [comment]
Hi @kevinpapst 

I have also posted an issue to Softaculus
https://softaculous.deskuss.com/tickets.php?id=237519

and they replied that something is wrongly setup on my server ot that I can try your last solution
https://github.com/kevinpapst/kimai2/blob/master/config/packages/prod/doctrine.yaml#L31

I am on a hosting platform, where I did nothing special to server settings and also I do not have access.
This fix you propose seems to be part of Kimai code Softaculus uses, but for normal GUI hosting user might be an overhead.

Please, update the proper and final solution on their task as I can see there are two options:
- Minimum PHP 8.0 and no change to Kimai package 1.16.10
- Minimum PHP 7.3 and this doctrine change in either Softaculus package or using new release of Kimai

I have no interest of testing PHP 7.3 as I have no test environment, sorry.

But I do wish other users might not get same issues with Error 503 as I think many more hosting users might be using Kimai.

I do like Kimai for now. Wish you all the best.

**Comment by kevinpapst** [comment]
> update the proper and final solution on their task

What? There is no "final solution" as this is a bug not even fixed in Doctrine, where it (as it seems by now) originally comes from. 

Using PHP8 seems to be the only known proper fix. 

Everything else is try and error and here for users who want to help debug the cause. This is still open source and everyone using it can and even should help => yes, I am talking to you Softaculous company!

**Comment by darkol** [comment]
@kevinpapst Thank you for your clarification. I tried my best to help Kimai by reporting my Use case. Thanks again for Kimai :)

I will update Softaculus issue that PHP8 seems to be the only known proper fix for now.
And will forward your thought on helping as I am not affiliated to Softaculus.

**Comment by brijeshk89** [comment]
> > update the proper and final solution on their task
> 
> What? There is no "final solution" as this is a bug not even fixed in Doctrine, where it (as it seems by now) originally comes from.
> 
> Using PHP8 seems to be the only known proper fix.
> 
> Everything else is try and error and here for users who want to help debug the cause. This is still open source and everyone using it can and even should help => yes, I am talking to you Softaculous company!

Hi,

I am from the Softaculous team. 

Do you recommend to set the minimum requirement to use Kimai to PHP 8.0 ?

**Comment by kevinpapst** [comment]
@brijeshk89 Can you safely reproduce the problem on other Softaculous servers with 7.3 / 7.4? 
Kimai works successful for thousands of user with the older PHP 7.3/4 versions. 
Just because a handful of user ran into this exotic issue should not cause troubles for everyone else who - for whatever  reason - is still bound to PHP7. Or does Softaculous support multiple PHP version per server / a different PHP version per app? If yes, then this requirement would be okay. 
If not I would (for now) argue against, because only a tiny minority of all users is affected.

**Comment by brijeshk89** [comment]
@kevinpapst I Agree. We could not replicate the issue on our test servers with PHP 7.3 and we would also not want to set the minimum PHP requirement to 8.0

It does not seem to be a PHP version but rather a PHP or some other server configuration that could have caused the issue. @darkol does not have a PHP 7.3 environment setup for now as per his previous response but if someone else faces this issue and can share access to the environment we would be happy to take a look and find the exact cause of the issue. 

I'm sure even @kevinpapst would be interested to take a look and find the exact cause of the issue. 

For now we will not be making any changes to the Kimai package in Softaculous.

**Comment by pbksol** [comment]
So… One Update later and things look promising.

Updated to Kimai 1.17.1 today which did update the dependencies, too. The ORM Version.php shows 2.7.1-DEV and the files date is January 12th.

It seems as if the 503s are gone running PHP8. I was not able to duplicate them anymore. I'll keep it watched ;-)

**Comment by greemo** [comment]
I have the same issue. 

Running Kimai 1.17.1 via softaculous on cloudamo. PHP 7.4.27

Upgrading to PHP 8.0 fixed the issue

**Comment by CordMemescape** [comment]
I have the same issue.

Running Kimai 1.18.1 (fresh installation) on PHP 7.4.28

Upgrading to PHP 8.1.3 resolved the problem.

Thanks to everyone above for the suggestion of upgrading to PHP 8 - I'd spent a few hours trying to debug and fix on my own before I found this thread.

**Comment by kevinpapst** [comment]
Hm, I thought 1.18 fixed the issue by upgrading Doctrine. Mysterious... 

Anyways: PHP 8.1 is not officially supported and does definitely not work with LDAP.

**Comment by CordMemescape** [comment]
Thanks for the feedback @kevinpapst - I'm not using LDAP but fortunately, have not encountered any further errors since upgrading to PHP 8.1. I'll downgrade to PHP 8.0 if I notice anything peculiar.

**Comment by kevinpapst** [comment]
Just in case anyone still hits this issue: 8.1 is officially supported with LDAP now.

**Comment by backhausmartin** [comment]
Hello,
I just ran into the same problem above upgrading from Kimai2 Kimai 1.14.1 to 1.26.0

After the cache is cleared, and I go to the my bookmarked main page at .../en/calendar/ it first works, but after a few clicks, waiting maybe 30sec, going back to the same URL throws a 503 Service unavailable error.

I went from PHP 7.4 to 8.1 - with both versions it does not work.

Going to PHP 8.0 it is now working and I can refresh the page successfully (PHP 8.0.20) multiple times in the last 10min.

Indeed one of the last error messages in var/log/prod.log is:

`request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing [...] Column not found: 1054 Unknown column 't0.account' in 'field list'" [...]`

and also

`php.CRITICAL: Uncaught Error: Argument 1 passed to Nelmio\CorsBundle\EventListener\CorsListener::__construct() must implement interface Nelmio\CorsBundle\Options\ResolverInterface, instance of Symfony\Component\EventDispatcher\EventDispatcher given [...]`

But those errors were not thrown again later, maybe only happened during the db migration and not related...

Maybe something happens in PHP 7.4 and 8.1 that is not present in 8.0...

(Otherwise the update is looking good, especially the new /quick_entry - thanks!)
